default: &default
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: api
  pool: 5
  username: postgres
  password: postgres123
  port: 5432

development:
  <<: *default
  database: api
